Move tests to catch2
Statoil/nex pull request #11
Opened 2018-01-17 07:31 UTC by sveinung-r

2018-01-17 07:39 UTC, ReedOnly commented
test this please

2018-01-30 14:02 UTC, JensGM requested changes
I found 3 missing commas, you should take a quick look incase there are more.

2018-01-30 14:02 UTC, JensGM commented on lib/tests/load.cpp
> +TEST_CASE( "load" "[load]") {
Missing comma, use `TEST_CASE( "load" "[load]")`

2018-01-30 14:02 UTC, JensGM commented on lib/tests/spe1.cpp
> +SCENARIO( "spe1" "[spe1]") { WHEN( "loading nexus plot file" ) {
Missing comma

2018-01-30 14:02 UTC, JensGM commented on lib/tests/units.cpp
> +TEST_CASE( "unit conversions" "[units]") {
Missing comma

2018-02-14 12:20 UTC, closed without merging